# ==================================================
# Entysquare DEX API V2 - Example Configuration
# ==================================================
# This is the template configuration for DEX API V2
# 
# Major changes in V2:
# 1. New D1 database with 15 tables for authentication and analytics
# 2. API key-based authentication system
# 3. Scheduled cron jobs for data synchronization
# 4. Permission-based access control with subscription tiers
# 5. Comprehensive rate limiting and usage tracking
#
# Setup Instructions:
# 1. Copy this file to wrangler.toml
# 2. Replace YOUR_*_HERE placeholders with actual values
# 3. Create D1 databases: wrangler d1 create d1-dex-database
# 4. Run migrations: npm run migrate:local
# 5. Initialize data: npm run db:init
# ==================================================

name = "dex-backend-serverless"
main = "src/index.ts"
compatibility_date = "2025-06-20"
compatibility_flags = ["nodejs_compat"]

# Replace with your Cloudflare account ID
account_id = "YOUR_ACCOUNT_ID_HERE"

# Database configuration for DEX V2
[[d1_databases]]
binding = "D1_DATABASE"
database_name = "d1-dex-database"
database_id = "YOUR_NEW_DEX_DATABASE_ID_HERE"
migrations_dir = "drizzle"

# Scheduled jobs for data sync
[[triggers.crons]]
name = "sync-pools-frequent"
cron = "*/5 * * * *"  # Every 5 minutes

[[triggers.crons]]
name = "sync-stats-hourly"
cron = "0 * * * *"  # Every hour

[[triggers.crons]]
name = "cleanup-old-data"
cron = "0 2 * * 0"  # Weekly on Sunday at 2 AM

# Environment variables
[vars]
KEY = "YOUR_SECRET_KEY_HERE"
NODE_ENV = "development"

# RPC endpoints for blockchain interaction
BSC_RPC_URL = "https://bsc-dataseed1.binance.org/"
BSCTEST_RPC_URL = "https://data-seed-prebsc-1-s1.binance.org:8545/"

# LiquiBook Factory contract addresses
LB_FACTORY_BSC = "0x8e42f2F4101563bF679975178e880FD87d3eFd4e"
LB_FACTORY_BSCTEST = "0x8e42f2F4101563bF679975178e880FD87d3eFd4e"

# Router contract addresses
LB_ROUTER_BSC = "0xb4315e873dBcf96Ffd0acd8EA43f689D8c20fB30"
LB_ROUTER_BSCTEST = "0xb4315e873dBcf96Ffd0acd8EA43f689D8c20fB30"

# Quoter contract addresses
LB_QUOTER_BSC = "0xfb76e9E7d88E308aB530330eD90e84a952570319"
LB_QUOTER_BSCTEST = "0xfb76e9E7d88E308aB530330eD90e84a952570319"

# Price API configuration
PRICE_API_URL = "https://api.coingecko.com/api/v3"
PRICE_API_KEY = "your-price-api-key-here"

# API rate limiting
API_RATE_LIMIT = "100"

# Optional bindings - configure for production
# Cloudflare AI binding for AI functionality
# [ai]
# binding = "AI"

# R2 Storage binding for file storage
# Create a new R2 bucket using: wrangler r2 bucket create dex-storage
# [[r2_buckets]]
# binding = 'R2'
# bucket_name = 'YOUR_BUCKET_NAME_HERE'
# preview_bucket_name = 'YOUR_PREVIEW_BUCKET_NAME_HERE'
